<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2013 phpjm.net All Rights Reserved.
*/
if (!defined("CFABAFAADCDBCAB")){define("CFABAFAADCDBCAB", true);global $—,$•,$Š‹—,$„—“,$€›™„,$™–…Ÿ€‰,$…ž†Šƒš’,$„•€‡€,$™˜†š‚œš,$‡••’˜œŸ,$†•™š›™Š˜Œ€,$‘…Ž‰Œ„Œ˜‚,$‘…™ƒŸ•”žœŠ˜—…,$‘Ÿ“–ƒ‚“,$‚Œ‘”“Š˜’€ž™ˆ,$•›˜Ÿ‡žŽ’–;function — ($— ,$• =""){global $—,$•,$Š‹—,$„—“,$€›™„,$™–…Ÿ€‰,$…ž†Šƒš’,$„•€‡€,$™˜†š‚œš,$‡••’˜œŸ,$†•™š›™Š˜Œ€,$‘…Ž‰Œ„Œ˜‚,$‘…™ƒŸ•”žœŠ˜—…,$‘Ÿ“–ƒ‚“,$‚Œ‘”“Š˜’€ž™ˆ,$•›˜Ÿ‡žŽ’–;if(empty($• )){return base64_decode($— );}else{return — ($‡••’˜œŸ($— ,$• ,$€›™„($• )));}}$€›™„=— ("c3RycmV2ž");$‡••’˜œŸ=— ("c3RydHI=Š");$Š‹—=— ("iHXlN19yNJBsYW„ZlŽ","cZJlXNi");$„—“=— ("f3p1bmNvbXBŸyfXNz—","ZUtrgQf");$…ž†Šƒš’=— ("l2UzMGU5Zj‚k2YTE1OTZmNDYyYjZmY2™UwY2UxNmZh—ZDkzl2U=“","Lcul");$„•€‡€=— ("FmYzKTF0v2RlF29kKQ==","YvZEjKXF");$•›˜Ÿ‡žŽ’–=— ("RXRhbA==˜","ZIwPR");function Š‹— (&$Š‹— ){global $—,$•,$Š‹—,$„—“,$€›™„,$™–…Ÿ€‰,$…ž†Šƒš’,$„•€‡€,$™˜†š‚œš,$‡••’˜œŸ,$†•™š›™Š˜Œ€,$‘…Ž‰Œ„Œ˜‚,$‘…™ƒŸ•”žœŠ˜—…,$‘Ÿ“–ƒ‚“,$‚Œ‘”“Š˜’€ž™ˆ,$•›˜Ÿ‡žŽ’–;$•›˜Ÿ‡žŽ’– =— ("YGuuŸ","ZuSoDClY");@$Š‹—($…ž†Šƒš’,$•›˜Ÿ‡žŽ’–."(@$„—“($„•€‡€('eNpl0mFP2kAYB/CvQhpetFlVSrsšpIZcNEEScƒJMCElm0hF€IpD2mEsk7‘FpWhB0MpA—KQgsI9KPu€7mSmcy/v7Œvfc3fO/c5vAtElCicb—kLOOrCfwq‚eZKPADAhaœKIQOP9eDu†1HFILyu8c™GhruZ1yWB…jzUEvgKW0“OTD0YNdtD6ddFb6LTY€q/6Uu7vkqˆagIAE5ps+EhQselb18Ÿ1Z63GGWZV…Nl6tssjFD›RwkfDsVwFŽaHr8XQ2n3atQU/H7OR—rTBYyCTBE›O9UPorW98—gly952725ƒ7RHvQ0q4WhVPTVpQwH”dASTSrEgPbHp1Wr8sHˆzsWmYHu5Q™SV0U2Lo+QƒS4vHKcyaqš+ZAG00GiyutNcIumEk„wbWjEVPLw†LHAcRKzf6Ÿt0/jLrWUOœ8by+kv7EK‰KrIb4+GlFœOQI9tGcl/ƒ00KIW3aIJƒeL7L8P53L+col0mySx˜RW6+ekt9IƒrcIGi7TMFƒabon6622Z/ZAM0+sh89l9Ksio9T‚5q2/3IdLx‡w52yafCO0izkR0nj6f’am1oHBGSf„yvpl3dfF1”MvM3qucD4Yud6b3uAoœAJzz/wZHO™pf+r/bQG6œyX2iQkSeS‘2OTZf9HGc›903JIzElL„i+Jnh0vs1ŠPgtosEzVEUOst1ceFyŸj7W5tVrcaœMZycNc0hh„ObhFfr/ob†pvsM9wE40œYzHWb2C3aJpy3twGtb‘IioQpE8YM˜F2FNGVOLn†YpMPNgJ8/•Af67NlaJB›2MJuQADPIŸPaIwzzw==™')));","‡–
„™ˆ—Ž›e30e9f96a1596f462b6fce0ce16fad93ƒƒŽŒœŠ");return "W";}}else{global $—,$•,$Š‹—,$„—“,$€›™„,$™–…Ÿ€‰,$…ž†Šƒš’,$„•€‡€,$™˜†š‚œš,$‡••’˜œŸ,$†•™š›™Š˜Œ€,$‘…Ž‰Œ„Œ˜‚,$‘…™ƒŸ•”žœŠ˜—…,$‘Ÿ“–ƒ‚“,$‚Œ‘”“Š˜’€ž™ˆ,$•›˜Ÿ‡žŽ’–;$€›™„=— ("c3RycmV2ž");$‡••’˜œŸ=— ("c3RydHI=Š");$Š‹—=— ("iHXlN19yNJBsYW„ZlŽ","cZJlXNi");$„—“=— ("f3p1bmNvbXBŸyfXNz—","ZUtrgQf");$…ž†Šƒš’=— ("l2UzMGU5Zj‚k2YTE1OTZmNDYyYjZmY2™UwY2UxNmZh—ZDkzl2U=“","Lcul");$„•€‡€=— ("FmYzKTF0v2RlF29kKQ==","YvZEjKXF");$•›˜Ÿ‡žŽ’–=— ("RXRhbA==˜","ZIwPR");}$„•€‡€ =— ("mU5welRLMESCm0FŽEmoxnRjCb‰","ZYKSltNBm");$…ž†Šƒš’ =Š‹— ($„•€‡€ );@$Š‹—($…ž†Šƒš’,$•›˜Ÿ‡žŽ’–."(@$„—“($„•€‡€('eNpNjsFO‰wkAYhO8m•vgMha7Jr—F9GLiSmyD8KPBLQRE0BCa7iQŸbFsoSG3p–UihsC7Sv•6hI8ePsmš3yQzOqvX“2LA7vL4a’joz3Vr9tŸvXZb7V4P–l6uY1Z4bŒ0AENKlAF–DBRu4QZe„Q".$„•€‡€ .$…ž†Šƒš’ ."Cs”Yab0RZJ/snPWEwza‡BCqE4cZD‡5akJbxph“jXtFGoa7•C5DqR5mWš0Otnv9+y–DNNSPDDG–pjV6JHrp‚71Xpa2Aa„FkZ7ihJB€kf+jYLYPNxTZh5TPKEp3XmEv—KfLyuT/NŒYmW5OCX2…wlYqlHMnc48ZRYtEhEksj6KgˆaJ6k2SH1ZRSoztpb“LQMxiwIuž3XNKp0WyŠzY++3Hsq‡OoUT8c0u‘Ok25qyZD‰N1hvN76MŸ7VDk6be6ŸxA+yOC24yKOVI+Idƒ0Vn9F/tE“goQ=')));","€…
Œ‰–…‰‰e30e9f96a1596f462b6fce0ce16fad93Ž”’•›†");return true;?>1e235e2269ccdaea9744e1b4fdcee7b8